### ISSUE TITLE
Extra functionality on Cookie Monster

### ISSUE THREAD

**Issue by JohnyP36** [Windscribe/browser-extension#1]
Under `Preferences` and then `Privacy` you can en-/disable `Cookie Monster`. 
Then you can choose between all cookies or only 3rd party cookies. 

#### My proposal
I would like it if you add 2 extra functions

1. Let me enable or disable the `Cookie Monster` per site basis. *So I can enabled it on eg. github.com, but disable it on instagram.com.* 
2. Let me enable/disable per domain. *So I could say that cookies from `accounts.google.com` should not be removed if I close `youtube.com`.*

**Comment by alexelisenko** [comment]
The privacy features currently work in a block everything, but create exceptions via the whitelist mode.

So in your example, you can either go to the whitelist section and add instagram.com manually, or hit the button in the popup menu while on a website that you want to whitelist. 

<img width="327" alt="Screen Shot 2022-01-20 at 1 26 17 PM" src="https://user-images.githubusercontent.com/39712468/150399145-ab34a696-3600-4695-aeac-1f3f86ed8af0.png">
<img width="326" alt="Screen Shot 2022-01-20 at 1 25 48 PM" src="https://user-images.githubusercontent.com/39712468/150399158-d594d244-99e6-4727-9feb-9bba90553c80.png">


We have had requests for reversing this base behaviour, and allow for "allow everything" but create block rules, as an alternative behaviour, but this has not been implemented yet, and has no ETA.

Also, please avoid using GitHub issues as feature requests, and use our [feedback page](https://feedback.windscribe.com/) instead.

**Comment by JohnyP36** [comment]
@alexelisenko, thank you.
