### ISSUE TITLE
Remove "Block element" from context menu while using Windscribe extension

### ISSUE THREAD

**Issue by DeFaLT-dj** [Windscribe/browser-extension#2]
I am using Windscibe extension on Edge and there is a block element selection appearing in context menus. I looked into extension settings but couldn't find any option to turn it off. Can you tell me how to turn it off if it is possible? 

This is the selection I am talking about.

![image](https://user-images.githubusercontent.com/64617514/150372097-c8510e29-b57a-44a5-b8bf-20d95cc8c0bb.png)

**Comment by alexelisenko** [comment]
This is a feature of the network and DOM level blocker we use under the hood (uBlock Origin). You can disable this feature by enabling the "Advanced Mode" under Preferences -> Blocker -> Advanced Mode, then open the uBlock Settings and uncheck the "Make use of context menu where appropriate" box.

<img width="324" alt="Screen Shot 2022-01-20 at 1 35 49 PM" src="https://user-images.githubusercontent.com/39712468/150400894-b7fdebe6-bd76-4f51-a6cd-9d4315c42289.png">

<img width="408" alt="Screen Shot 2022-01-20 at 1 30 03 PM" src="https://user-images.githubusercontent.com/39712468/150400731-4b5b0101-9586-4b3c-a544-ba450a9c0555.png">

Please avoid using GitHub issues as support questions. You will have much better response time contacting [support](https://windscribe.com/support)
